a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
print ("the sum of a nd b is:",(a+b))
print ("the sub of a nd b is:",(a-b))
print ("the div of a nd b is:",(a/b))
print ("the mul of a nd b is:",(a*b))
print ("the rem of a nd b is:",(a//b))
print("the power of a and b is :",(a**b))
